### ISSUE TITLE
Знакомство с github

### ISSUE THREAD

**Issue by irinabloaschinskaya** [irinabloaschinskaya/mofm#5]
Под этой задачей оставляете ссылку на созданный вами репозиторий где вы делали задания.
Ссылка на обучающую страницу: https://guides.github.com/activities/hello-world/

дедлайн 21.11

**Comment by DimaOsad23** [comment]
https://github.com/DimaOsad23/hello-world/issues

**Comment by AberKadaber** [comment]
https://github.com/LeviyCvesium/hellow-world

пт, 20 нояб. 2020 г. в 17:43, DimaOsad23 <notifications@github.com>:

**Comment by BlackKek1** [comment]
https://github.com/BlackKek1/hello-world

**Comment by irinabloaschinskaya** [comment]
познакомились
